# Generated by Django 4.2.7 on 2024-05-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0037_poll_parent_alter_poll_poll_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='approval_minimum',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='finalization_period',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
