# Generated by Django 4.2.7 on 2024-05-20 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0039_alter_poll_approval_minimum'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='finalization_period_start',
            field=models.DateTimeField(blank=True, default=None, help_text='Datetime when finalization period began', null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='finalization_period',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Finalization period in days', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='poll',
            name='quorum',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
