# Generated by Django 4.2.7 on 2024-06-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0042_rename_finalization_period_start_poll_finalization_period_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='approval_minimum',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='finalization_period',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='quorum',
        ),
    ]
