# Generated by Django 4.2.7 on 2024-06-04 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0026_grouppermissions_poll_fast_forward'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='approval_minimum',
            field=models.PositiveIntegerField(default=51, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='group',
            name='finalization_period',
            field=models.PositiveIntegerField(default=3, help_text='Finalization period in days', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='group',
            name='default_quorum',
            field=models.PositiveIntegerField(default=51, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
